[project]
name = "taxi-demand-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "python-dotenv",
    "jupyter",
    "jupyterlab",
    "pandas",
    "pyarrow",
    "tqdm",
    "plotly",
    "scikit-learn",
    "xgboost",
    "lightgbm",
    "optuna",
    "ruff",
    "hopsworks",
]